### ISSUE TITLE
Baidu Cloud alternative?

### ISSUE THREAD

**Issue by maltebaumann** [aisegmentcn/matting_human_datasets#2]
Hey and thank you for making this dataset available. Unfortunately, accessing the Baidu Cloud from outside of China is really hard, as a chinese mobile number is required. Is there any chance you could upload the data somewhere else? Thanks!

**Comment by aisegmentcn** [comment]
OK, I will try to upload to google drive recently.

**Comment by siebenzwiebel** [comment]
I am currently downloading the dataset and will try to upload it to something more accessible for non-chinese people. I'll let you know once I'm finished.

**Comment by aisegmentcn** [comment]
@stevendrewers Thank you very much! Please cite our github address, thanks.

**Comment by siebenzwiebel** [comment]
I just managed to upload it to mega.co.nz. If anyone knows a better filehoster, that allows me to upload file with ~15GB, feel free to let me know! 

I added a markdown file containing the github link. Here's the folder: 

https://mega.nz/#F!Gh8CFAyb!e2ppUh-copP76GbE8IWAEQ

Please let me know, if the citation is sufficient, and maybe add the link to your readme?

EDIT: I updated the link. Didn't know you needed an encryption key. :)

**Comment by aisegmentcn** [comment]
@stevendrewers OK, you needn't add the link to our readme.
I will show your url in readme :)

**Comment by maltebaumann** [comment]
Just found the new link. Thanks a lot!

**Comment by laurentmih** [comment]
Because I also ran into the issue of accessing Baidu, and at the same time, the MEGA download is limited to 5GB per user, I've also uploaded the dataset to Kaggle:   https://www.kaggle.com/laurentmih/aisegmentcom-matting-human-datasets/

This should allow for easy downloading for anyone, and improve discoverability (this is a great dataset!).

I hope that's acceptable. I've linked to this GitHub to make sure you are credited. Could you take a quick glance over it and let me know if it's okay? If you create a corporate structure on Kaggle I'm of course happy to transfer it under that umbrella too.

**Comment by aisegmentcn** [comment]
Hello, @laurentmih . I am glad to share this datasets to more researchers. Thank you for sharing onto Kaggle. I will cite this kaggle url in our readme.
